# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442', 'verbose_name_plural': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442\u0438'},
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
